<?php
return [
    'sosial_media_tipe' => [
        'facebook',
        'instagram',
        'youtube',
        'twitter',
        'whatsapp'
    ],
    'post' => [
        'berita',
        'lkk',
        'bencana',
        'potensi'
    ],
    'pendidikan' => [
        'SLTA / SEDERAJAT',
        'SLTP/SEDERAJAT',
        'TIDAK / BELUM SEKOLAH',
        'TAMAT SD / SEDERAJAT',
        'BELUM TAMAT SD/SEDERAJAT',
        'DIPLOMA IV/ STRATA I',
        'AKADEMI/ DIPLOMA III/S. MUDA',
        'STRATA II',
        'DIPLOMA I / II',
        'STRATA III',
    ],

    'pendidikan_ditempuh' => [
        'SEDANG TK/KELOMPOK BERMAIN',
        'SEDANG S-2/SEDERAJAT',
        'BELUM MASUK TK / KELOMPOK BERMAIN',
        'SEDANG S-1/SEDERAJAT',
        'SEDANG D-3/SEDERAJAT',
        'SEDANG D-2/SEDERAJAT',
        'SEDANG D-1/SEDERAJAT',
        'SEDANG SLTA/SEDERAJAT',
        'SEDANG SD/SEDERAJAT',
        'TIDAK DAPAT MEMBACA DAN MENULIS',
        'SEDANG SLTP/SEDERAJAT',
        'SEDANG SLB C/SEDERAJAT',
        'TIDAK TAMAT SD/SEDERAJAT',
        'TIDAK SEDANG SEKOLAH',
    ],

    'konten' => [
        'visi_misi',
        'profil_dan_wilayah',
        'pamong_kalurahan',
        'kepala_desa',
        'badan_permusyawaratan',
        'sejarah_kalurahan',
        'gambaran_umum',
        'layanan_kesehatan'
    ],
    'gol_darah' => [
        'TIDAK TAHU',
        'O',
        'B',
        'A',
        'AB',
        'AB-',
        'A+',
        'B-',
        'O+',
        'A-',
        'AB+',
        'O-',
        'B+',
    ],
    'gol_darah' => [
        'TIDAK TAHU',
        'O',
        'B',
        'A',
        'AB',
        'AB-',
        'A+',
        'B-',
        'O+',
        'A-',
        'AB+',
        'O-',
        'B+',
    ],
    'kawin' => [
        'KAWIN',
        'BELUM KAWIN',
        'CERAI MATI',
        'CERAI HIDUP',
    ],
    'agama' => [
        'ISLAM',
        'KRISTEN',
        'KATHOLIK',
        'HINDU',
        'BUDHA',
        'KHONGHUCU',
        'Kepercayaan Terhadap Tuhan YME / Lainnya',

    ],
    'hub_keluarga' => [
        'ANAK',
        'baik',
        'CUCU',
        'FAMILI LAIN',
        'ISTRI',
        'KEPALA KELUARGA',
        'LAINNYA',
        'MENANTU',
        'MERTUA',
        'ORANGTUA',
        'PEMBANTU',
        'SUAMI',


    ],
    'pekerjaan' => [
        'PELAJAR/MAHASISWA',
        'BELUM/TIDAK BEKERJA',
        'KARYAWAN SWASTA',
        'MENGURUS RUMAH TANGGA',
        'BURUH HARIAN LEPAS',
        'WIRASWASTA',
        'PEGAWAI NEGERI SIPIL (PNS)',
        'PENSIUNAN',
        'PETANI/PERKEBUNAN',
        'PERDAGANGAN',
        'GURU',
        'BURUH TANI/PERKEBUNAN',
        'PEDAGANG',
        'KEPOLISIAN RI (POLRI)',
        'KARYAWAN HONORER',
        'TENTARA NASIONAL INDONESIA (TNI)',
        'LAINNYA',
        'KARYAWAN BUMN',
        'DOSEN',
        'KONSTRUKSI',
        'INDUSTRI',
        'PERAWAT',
        'KARYAWAN BUMD',
        'PERANGKAT DESA',
        'DOKTER',
        'SOPIR',
        'TUKANG BATU',
        'TUKANG KAYU',
        'TUKANG JAHIT',
        'MEKANIK',
        'SENIMAN',
        'BIDAN',
        'PEMBANTU RUMAH TANGGA',
        'TRANSPORTASI',
        'KONSULTAN',
        'PETERNAK',
        'WARTAWAN',
        'PELAUT',
        'TUKANG LAS/PANDAI BESI',
        'PENATA RIAS',
        'PENGACARA',
        'ARSITEK',
        'BURUH PETERNAKAN',
        'PENATA RAMBUT',
        'APOTEKER',
        'BIARAWATI',
        'PENDETA',
        'USTADZ/MUBALIGH',
        'PENELITI',
        'KEPALA DESA',
        'TUKANG LISTRIK',
        'BURUH NELAYAN/PERIKANAN',
        'TUKANG CUKUR',
        'PASTOR',
        'NELAYAN/PERIKANAN',
        'JURU MASAK',
        'NOTARIS',
        'BUPATI',
        'ANGGOTA DPR-RI',
        'PRESIDEN',
        'PARANORMAL',
        'ANGGOTA KABINET KEMENTERIAN',
        'AKUNTAN',
        'PARAJI',
        'WAKIL GUBERNUR',
        'IMAM MASJID',
        'WALIKOTA',
        'PSIKIATER/PSIKOLOG',
        'TUKANG SOL SEPATU',
        'PROMOTOR ACARA',
        'ANGGOTA DPRD KABUPATEN/KOTA',
        'TUKANG GIGI',
        'ANGGOTA BPK',
        'PILOT',
        'PIALANG',
        'ANGGOTA MAHKAMAH KONSTITUSI',
        'TABIB',
        'GUBERNUR',
        'PENTERJEMAH',
        'WAKIL BUPATI',
        'ANGGOTA DPRD PROVINSI',
        'PENYIAR RADIO',
        'ANGGOTA DPD',
        'PENATA BUSANA',
        'WAKIL PRESIDEN',
        'DUTA BESAR',
        'PERANCANG BUSANA',
        'WAKIL WALIKOTA',
        'PENYIAR TELEVISI',
    ]




];
